#!/bin/bash
#PBS -l nodes=1:ppn=2,walltime=00:30:00
#PBS -N concatenate-tractmeasures
#PBS -V

singularity exec -e docker://brainlife/freesurfer-stats:1.2 ./concatenate-tractmeasures.py

if [ ! -f ./output/tractmeasures.csv ]; then
    echo "something failed. checked logs"
    exit 1
else
    echo "complete"
    exit 0
fi
